# Generated by Django 5.1.1 on 2024-09-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_hesh_cars_teg'),
    ]

    operations = [
        migrations.AddField(
            model_name='hesh',
            name='name_link',
            field=models.CharField(max_length=50, null=True, verbose_name='ссылка'),
        ),
    ]
