# Generated by Django 5.1.1 on 2024-09-24 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_hesh_name_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hesh',
            name='name_link',
        ),
    ]
