# Generated by Django 5.1.1 on 2024-09-24 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_remove_hesh_name_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetWorkLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='название')),
                ('name_link', models.CharField(max_length=40, verbose_name='ссылка')),
                ('cars', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='cars.cars', verbose_name='ссылка')),
            ],
        ),
    ]
