# Generated by Django 5.1.1 on 2024-10-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_cars_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='is_publish',
            field=models.BooleanField(default=True, verbose_name='публикация'),
        ),
        migrations.AddField(
            model_name='cars',
            name='updata',
            field=models.DateField(auto_now=True, verbose_name='Изменить дату'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='data',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='teg',
            field=models.ManyToManyField(blank=True, related_name='cars', to='cars.hesh', verbose_name='теги'),
        ),
    ]
